services:

    paypal.processor:
        class: Systemeio\TestForCandidates\PaymentProcessor\PaypalPaymentProcessor

    Systemeio\TestForCandidates\PaymentProcessor\PaypalPaymentProcessor:
        alias: paypal.processor

    stripe.processor:
        class: Systemeio\TestForCandidates\PaymentProcessor\StripePaymentProcessor

    Systemeio\TestForCandidates\PaymentProcessor\StripePaymentProcessor:
        alias: stripe.processor